#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.0
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestApp.Android.Resource", IsApplication=true)]

namespace TestApp.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int CTextView = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int Frag_Button = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int Frag_InputText = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int Frag_TW = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int GreetingText = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int MainFragmentContainer = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int MyButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int ZAutoGenerated_084ed1e08c2ef4e0308751d475adea968496a8d84609217318df69f2a637b96f = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ZAutoGenerated_aec66ed9ded059a0f768db58f85f2bcd21612315577313c9e0ad724e1bcb5aaf = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int ZAutoGenerated_b13fb8dba7402fb5179dbefcddf69a3ba76351f62718c623a25954633d4f93ac = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int ZAutoGenerated_e7ebf3a8e935b53855d0b6038cbfac62caca6371cdbc82b0c5b0ce7d58bff2b8 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int ZAutoGenerated_fbbd374cbcc79f242db25d2f371ac61c36b13d4b7b0fd778e4ddbd3aef453f89 = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Second = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
